#+title: Rust Training
#+description: Small mini projects based on rust pl.
#+author: Elohim


* Summary
This contain small rust based projects. The purpose of this repo is to learn some rust and have some fun at the same time. Feel free to comment and give some ideas.
* Projects
** Login.rs
Console application that gives a menu to user. The user must select the following options:
#+begin_src bash
SignIn
LogIn
Quit
#+end_src
*** SignUn
A user record is created and with a username and password.
*** LogIn
Asks for username and if it exists, then asks for password. This returns a ~User struct~.
*** Quit
Exists the program
** Book_store.rs
Interactive console app, for book keeping records.
It asks for a book title, description and price, then save the record to a file.
#+begin_src bash
Add a record
List currents books in cache
Save books to file
Quit
#+end_src
** PNG File Structure
The intention of this project is to check  weather is posible to inject data into a png image wihout corrupting the file.

*Note*: /The png image used as test in this project is from [[https://en.wikipedia.org/wiki/Portable_Network_Graphics]wikipedia]/
*** Functions
**** ~is_png~
#+begin_src rust
use projects::png::png;
fn main(){
    let mut png = png::Png::new("PNG_transparency_demonstration_1.png");
    if png.is_png() {
        println!("This file is a png image");
    } else {
        println!("File is not a png image");
    }
}
#+end_src
